// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../AssemblyInfo.fs"
      "../Geometry.fs"
      "../Drawing.fs"
      "../View.fs"
      "../Cmd.fs"
      "../Ui.fs"
      "../Rectangle.fs"
      "../Arranged.fs"
      "../Mapped.fs"
      "../Padded.fs"
      "../Translated.fs"
      "../Overlayed.fs"
      "../Augmented.fs"
      "../Mouseover.fs"
      "../Bordered.fs"
      "../Program.fs"
